services:
  backend-1:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2026-dotnet-csharp-with-faiss:20260510185837
    hostname: backend-1
    volumes:
      - sock:/run/sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LISTEN_SOCK=/run/sock/api-1.sock
      - ConnectionStrings__faiss=http://faiss-backend:5000
    cpuset: "2,3"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
  backend-2:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2026-dotnet-csharp-with-faiss:20260510185837
    hostname: backend-2
    volumes:
      - sock:/run/sock
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LISTEN_SOCK=/run/sock/api-2.sock
      - ConnectionStrings__faiss=http://faiss-backend:5000
    cpuset: "2,3"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
  faiss-backend:
    image: ghcr.io/micheloliveira-com/rinha-de-backend-2026-dotnet-csharp-with-python-faiss:20260510185837
    ports:
      - "5000"
    cpuset: "0,1"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "220MB"
  load-balancer:
    image: haproxy:3.3.8-alpine
    volumes:
      - sock:/run/sock
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend-1
      - backend-2
      - faiss-backend
    ports:
      - "9999:9999"
    cpuset: "2,3"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"