services:
  backend-1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: rinha-de-backend-2026-dotnet-csharp-with-faiss:latest
  backend-2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: rinha-de-backend-2026-dotnet-csharp-with-faiss:latest
  faiss-backend:
    build:
      context: faiss-backend
      dockerfile: Dockerfile
    image: rinha-de-backend-2026-dotnet-csharp-with-python-faiss:latest